//let urlHopital = "https://www.donneesquebec.ca/recherche/api/3/action/datastore_search?resource_id=a9272cc9-8234-40d1-9806-9f6b4c75c20d&limit=115"
//let urlChirurgie = "https://www.donneesquebec.ca/recherche/api/3/action/datastore_search?resource_id=7c83f4be-bc3a-4756-86db-115e8ead93f1&limit=100"

export const regionAdministrative = [
    {value: "01", code: "RSS01", key: 1, text: "Bas-Saint-Laurent"},
    {value: "02", code: "RSS02", key: 2, text: "Saguenay - Lac-Saint-Jean"},
    {value: "03", code: "RSS03", key: 3, text: "Capitale-Nationale"},
    {value: "04", code: "RSS04", key: 4, text: "Mauricie et Centre-du-Québec"},
    {value: "05", code: "RSS05", key: 5, text: "Estrie"},
    {value: "06", code: "RSS06", key: 6, text: "Montréal"},
    {value: "07", code: "RSS07", key: 7, text: "Outaouais"},
    {value: "08", code: "RSS08", key: 8, text: "Abitibi-Témiscamingue"},
    {value: "09", code: "RSS09", key: 9, text: "Côte-Nord"},
    {value: "10", code: "RSS10", key: 10, text: "Nord-du-Québec"},
    {value: "11", code: "RSS11", key: 11, text: "Gaspésie - Îles-de-la-Madeleine"},
    {value: "12", code: "RSS12", key: 12, text: "Chaudière-Appalaches"},
    {value: "13", code: "RSS13", key: 13, text: "Laval"},
    {value: "14", code: "RSS14", key: 14, text: "Lanaudière"},
    {value: "15", code: "RSS15", key: 15, text: "Laurentides"},
    {value: "16", code: "RSS16", key: 16, text: "Montérégie"}
]

export const nomEtablissement = [
    {value: "01", code: "01", key: 1, "text": "CISSS du Bas-Saint-Laurent"},
    {value: "02", code: "02", key: 2, "text": "CIUSSS du Saguenay - Lac-Saint-Jean"},
    {value: "03", code: "03", key: 3, "text": "CIUSSS de la Capitale-Nationale"},
    {value: "04", code: "03", key: 4, "text": "CHU"},
    {value: "05", code: "03", key: 5, "text": "Institut universitaire de cardiologie et de pneumologie de Québec"},
    {value: "06", code: "04", key: 6, "text": "CIUSSS de la Mauricie et du Centre-du-Québec"},
    {value: "07", code: "05", key: 7, "text": "CIUSSS de l'Estrie - Centre hospitalier de Sherbrooke"},
    {value: "08", code: "06", key: 8, "text": "CIUSSS de l'Ouest-de-l'Île-de-Montréal"},
    {value: "09", code: "06", key: 9, "text": "CIUSSS du Centre-Ouest-de-l'Île-de-Montréal"},
    {value: "10", code: "06", key: 10, "text": "CIUSSS du Centre-Sud-de-l'Île-de-Montréal"},
    {value: "11", code: "06", key: 11, "text": "CIUSSS du Nord-de-l'Île-de-Montréal"},
    {value: "12", code: "06", key: 12, "text": "CIUSSS de l'Est-de-l'Île-de-Montréal"},
    {value: "13", code: "06", key: 13, "text": "CHUM"},
    {value: "14", code: "06", key: 14, "text": "CUSM"},
    {value: "15", code: "06", key: 15, "text": "Institut de Cardiologie de Montréal"},
    {value: "16", code: "06", key: 16, "text": "CHU Sainte-Justine"},
    {value: "17", code: "07", key: 17, "text": "CISSS de l'Outaouais"},
    {value: "18", code: "08", key: 18, "text": "CISSS de l'Abitibi-Témiscamingue"},
    {value: "19", code: "09", key: 19, "text": "CISSS de la Côte-Nord"},
    {value: "20", code: "11", key: 20, "text": "CISSS de la Gaspésie"},
    {value: "21", code: "11", key: 21, "text": "CISSS des Îles"},
    {value: "22", code: "12", key: 22, "text": "CISSS de Chaudière-Appalaches"},
    {value: "23", code: "13", key: 23, "text": "CISSS de Laval"},
    {value: "24", code: "14", key: 24, "text": "CISSS de Lanaudière"},
    {value: "25", code: "15", key: 25, "text": "CISSS des Laurentides"},
    {value: "26", code: "16", key: 26, "text": "CISSS de la Montérégie-Centre"},
    {value: "27", code: "16", key: 27, "text": "CISSS de la Montérégie-Est"},
    {value: "28", code: "16", key: 28, "text": "CISSS de la Montérégie-Ouest"}    
]

export const nomInstallation = [
    {value: "01", code: "01", key: 1 , "text":"Hôpital de Matane"},
    {value: "02", code: "01", key: 2 , "text":"Centre hospitalier d'Amqui"},
    {value: "03", code: "01", key: 3 , "text":"Hôpital régional de Rimouski"},
    {value: "04", code: "01", key: 4 , "text":"Centre hospitalier Trois-Pistoles"},
    {value: "05", code: "01", key: 5 , "text":"Centre hospitalier régional du Grand-Portage"},
    {value: "06", code: "01", key: 6 , "text":"Hôpital de Notre-Dame-du-Lac"},
    {value: "07", code: "01", key: 7 , "text":"CLSC de Pohenegamook"},
    {value: "08", code: "01", key: 8 , "text":"Hôpital Notre-Dame-de-Fatima"},
    {value: "09", code: "02", key: 9 , "text":"Hôpital de La Baie"},
    {value: "10", code: "02", key: 10 , "text":"Hôpital de Chicoutimi"},
    {value: "11", code: "02", key: 11 , "text":"Hôpital et Centre de réadaptation de Jonquière"},
    {value: "12", code: "02", key: 12 , "text":"Hôpital d'Alma"},
    {value: "13", code: "02", key: 13 , "text":"Hôpital, CLSC et Centre d'hébergement de Roberval"},
    {value: "14", code: "02", key: 14 , "text":"Hôpital de Dolbeau-Mistassini"},
    {value: "15", code: "03", key: 15 , "text":"Hôpital régional de Portneuf et CLSC Saint-Raymond"},
    {value: "16", code: "03", key: 16 , "text":"CLSC Saint-Marc-des-Carrières"},
    {value: "17", code: "03", key: 17 , "text":"Hôpital Chauveau"},
    {value: "18", code: "03", key: 18 , "text":"Hôpital de Sainte-Anne-de-Beaupré"},
    {value: "19", code: "03", key: 19 , "text":"Hôpital de Baie-Saint-Paul"},
    {value: "20", code: "03", key: 20 , "text":"Hôpital de La Malbaie"},
    {value: "21", code: "04", key: 21 , "text":"Le Centre hospitalier de l'Université Laval"},
    {value: "22", code: "04", key: 22 , "text":"Hôpital Saint-François-d'Assise"},
    {value: "23", code: "04", key: 23 , "text":"L'Hôtel-Dieu de Québec"},
    {value: "24", code: "04", key: 24 , "text":"Hôpital de l'Enfant-Jésus"},
    {value: "25", code: "04", key: 25 , "text":"Hôpital du Saint-Sacrement"},
    {value: "26", code: "05", key: 26 , "text":"Institut universitaire de cardiologie et de pneumologie de Québec"},
    {value: "27", code: "06", key: 27 , "text":"CSSS du Haut-Saint-Maurice"},
    {value: "28", code: "06", key: 28 , "text":"Hôpital du Centre-de-la-Mauricie"},
    {value: "29", code: "06", key: 29 , "text":"Résidence Avellin-Dalcourt"},
    {value: "30", code: "06", key: 30 , "text":"Centre hospitalier régional de Trois-Rivières"},
    {value: "31", code: "06", key: 31 , "text":"Hôtel-Dieu d'Arthabaska"},
    {value: "32", code: "06", key: 32 , "text":"Hôpital Sainte-Croix"},
    {value: "33", code: "06", key: 33 , "text":"CLSC de Fortierville"},
    {value: "34", code: "06", key: 34 , "text":"Centre multiservices de santé et services sociaux Christ-Roi"},
    {value: "35", code: "07", key: 35 , "text":"Hôpital Fleurimont"},
    {value: "36", code: "07", key: 36 , "text":"Hôtel-Dieu"},
    {value: "37", code: "07", key: 37 , "text":"CSSS de Memphrémagog"},
    {value: "38", code: "07", key: 38 , "text":"CSSS de la MRC-de Coaticook"},
    {value: "39", code: "07", key: 39 , "text":"CSSS du Granit"},
    {value: "40", code: "07", key: 40 , "text":"Hôpital, CLSC et Centre d'hébergement d'Asbestos"},
    {value: "41", code: "07", key: 41 , "text":"Hôpital Brome-Missisquoi-Perkins"},
    {value: "42", code: "07", key: 42 , "text":"Centre hospitalier de Granby"},
    {value: "43", code: "08", key: 43 , "text":"Centre hospitalier de St. Mary"},
    {value: "44", code: "08", key: 44 , "text":"Institut universitaire en santé mentale Douglas"},
    {value: "45", code: "08", key: 45 , "text":"Hôpital de LaSalle"},
    {value: "46", code: "08", key: 46 , "text":"Hôpital général du Lakeshore"},
    {value: "47", code: "09", key: 47 , "text":"L'Hôpital général Juif Sir Mortimer B. Davis"},
    {value: "48", code: "10", key: 48 , "text":"Hôpital de Verdun"},
    {value: "49", code: "10", key: 49 , "text":"Hôpital Notre-Dame"},
    {value: "50", code: "11", key: 50 , "text":"Hôpital Fleury"},
    {value: "51", code: "11", key: 51 , "text":"Hôpital du Sacré-Coeur de Montréal"},
    {value: "52", code: "11", key: 52 , "text":"Hôpital Jean-Talon"},
    {value: "53", code: "11", key: 53 , "text":"Pavillon Albert-Prévost"},
    {value: "54", code: "12", key: 54 , "text":"Institut universitaire en santé mentale de Montréal"},
    {value: "55", code: "12", key: 55 , "text":"Hôpital Maisonneuve-Rosemont"},
    {value: "56", code: "12", key: 56 , "text":"Hôpital Santa Cabrini"},
    {value: "57", code: "13", key: 57 , "text":"Centre hospitalier de l'Université de Montréal"},
    {value: "58", code: "14", key: 58 , "text":"Hôpital Royal Victoria"},
    {value: "59", code: "14", key: 59 , "text":"Hôpital général de Montréal"},
    {value: "60", code: "14", key: 60 , "text":"Hôpital de Montréal pour enfants"},
    {value: "61", code: "14", key: 61 , "text":"Campus Lachine"},
    {value: "62", code: "15", key: 62 , "text":"Institut de Cardiologie de Montréal"},
    {value: "63", code: "16", key: 63 , "text":"CHU Sainte-Justine"},
    {value: "64", code: "17", key: 64 , "text":"Hôpital du Pontiac"},
    {value: "65", code: "17", key: 65 , "text":"Hôpital de Hull"},
    {value: "66", code: "17", key: 66 , "text":"Hôpital de Gatineau"},
    {value: "67", code: "17", key: 67 , "text":"Hôpital de Papineau"},
    {value: "68", code: "17", key: 68 , "text":"Hôpital Memorial de Wakefield"},
    {value: "69", code: "17", key: 69 , "text":"CLSC de Fort-Coulonge"},
    {value: "70", code: "17", key: 70 , "text":"Hôpital de Maniwaki"},
    {value: "71", code: "17", key: 71 , "text":"CLSC et Centre d'hébergement la Petite-Nation"},
    {value: "72", code: "18", key: 72 , "text":"Hôpital et CLSC de Val-d'Or"},
    {value: "73", code: "18", key: 73 , "text":"Centre hospitalier Hôtel-Dieu d'Amos"},
    {value: "74", code: "18", key: 74 , "text":"Centre hospitalier La Sarre"},
    {value: "75", code: "18", key: 75 , "text":"Centre hospitalier de Rouyn-Noranda"},
    {value: "76", code: "18", key: 76 , "text":"Pavillon Ste-Famille"},
    {value: "77", code: "18", key: 77 , "text":"Point de service de Temiscaming-et-de-Kipawa"},
    {value: "78", code: "19", key: 78 , "text":"Pavillon Forestville"},
    {value: "79", code: "19", key: 79 , "text":"Pavillon Escoumins"},
    {value: "80", code: "19", key: 80 , "text":"Hôpital Le Royer"},
    {value: "81", code: "19", key: 81 , "text":"Hôpital et Centre d'hébergement de Sept-Iles"},
    {value: "82", code: "19", key: 82 , "text":"CSSS de l'Hématite"},
    {value: "83", code: "19", key: 83 , "text":"CSSS de la Minganie"},
    {value: "84", code: "19", key: 84 , "text":"CSSS de la Basse-Côte-Nord"},
    {value: "85", code: "19", key: 85 , "text":"CSSS de Port-Cartier"},
    {value: "86", code: "20", key: 86 , "text":"Hôpital de Sainte-Anne-des-Monts"},
    {value: "87", code: "20", key: 87 , "text":"Hôpital de Maria"},
    {value: "88", code: "20", key: 88 , "text":"CLSC de Paspébiac"},
    {value: "89", code: "20", key: 89 , "text":"Hôpital de Chandler"},
    {value: "90", code: "20", key: 90 , "text":"Hôpital Hôtel-Dieu"},
    {value: "91", code: "20", key: 91 , "text":"CLSC de Grande-Vallée"},
    {value: "92", code: "20", key: 92 , "text":"CLSC de Murdochville"},
    {value: "93", code: "21", key: 93 , "text":"Hôpital de l'Archipel"},
    {value: "94", code: "22", key: 94 , "text":"Hôpital de Montmagny"},
    {value: "95", code: "22", key: 95 , "text":"Hôtel-Dieu de Lévis"},
    {value: "96", code: "22", key: 96 , "text":"Centre Paul-Gilbert - Centre d'hébergement de Charny"},
    {value: "97", code: "22", key: 97 , "text":"Hôpital de St-Georges"},
    {value: "98", code: "22", key: 98 , "text":"Hôpital de Thetford Mines"},
    {value: "99", code: "23", key: 99 , "text":"Hôpital Cité de la Santé"},
    {value: "100", code: "24", key: 100 , "text":"Hôpital Pierre-Le Gardeur"},
    {value: "101", code: "24", key: 101 , "text":"Centre hospitalier régional de Lanaudière"},
    {value: "102", code: "25", key: 102 , "text":"Hôpital de Saint-Eustache"},
    {value: "103", code: "25", key: 103 , "text":"Hôpital régional de Saint-Jérôme"},
    {value: "104", code: "25", key: 104 , "text":"CSSS d'Argenteuil"},
    {value: "105", code: "25", key: 105 , "text":"Hôpital Laurentien"},
    {value: "106", code: "25", key: 106 , "text":"Centre de services de Rivière-Rouge"},
    {value: "107", code: "25", key: 107 , "text":"Hôpital de Mont-Laurier"},
    {value: "108", code: "26", key: 108 , "text":"Hôpital Charles Lemoyne"},
    {value: "109", code: "26", key: 109 , "text":"Hôpital du Haut-Richelieu"},
    {value: "110", code: "27", key: 110 , "text":"Hôtel-Dieu de Sorel"},
    {value: "111", code: "27", key: 111 , "text":"Hôpital Honoré-Mercier"},
    {value: "112", code: "27", key: 112 , "text":"Hôpital Pierre-Boucher"},
    {value: "113", code: "28", key: 113 , "text":"Centre hospitalier Anna-Laberge"},
    {value: "114", code: "28", key: 114 , "text":"Hôpital Barrie Memorial"},
    {value: "115", code: "28", key: 115 , "text":"Hôpital du Suroît"}
]
